apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shilparg/shilpakk_argocd_3.13.git
    targetRevision: main
    path: manifest/helm/sample-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: shilpa-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
